### ISSUE TITLE
Mod Menu and Gameplay

### ISSUE THREAD

**Issue by DXUltimate** [ListenerJubatus/smtheme-fiftyOne#11]
Hello, I came across your theme as you mentioned it in the StepMania forums and wanted to report a few issues regarding it. =)

When attempting to play a song, attempting to enter the modifier menu would give this screen;

http://puu.sh/sawmc/df43b09975.jpg

However, completely skipping the modifiers and attempting to go into ScreenGameplay it would give this screen

http://puu.sh/sawuY/9b44474fc2.jpg and then render the stepchart as if it were being played on "0x"

http://puu.sh/sawwa/bd0eea663c.jpg

The version of StepMania I am using is 5.1.-3.

I've been meaning to report these thing earlier as they were issues in previous commits, but I kept getting sidetracked by other things.

**Comment by ListenerJubatus** [comment]
> The version of StepMania I am using is 5.1.-3.

There's your problem. It requires a nightly build, cause things have changed a bit since -3 (specifically, we have effects modifiers back in the menu now). Admittedly I should have mentioned this in the readme (it now does).

Go to https://ci.appveyor.com/project/wolfman2000/stepmania-wm87c/history , click a revision, and click the Artifacts link for the installer download.
